/*++

Copyright (C) 2023 Autodesk Inc.

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the Autodesk Inc. nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS' AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL AUTODESK INC. BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


This file has been generated by the Automatic Component Toolkit (ACT) version 1.8.0-develop.

Abstract: This is an autogenerated C++-Header file in order to allow an easy
 use of GRPC Library Wrapper

Interface version: 1.2.0

*/

#ifndef __LIBGRPCWRAPPER_DYNAMICHEADER_CPPTYPES
#define __LIBGRPCWRAPPER_DYNAMICHEADER_CPPTYPES

#include "libgrpcwrapper_types.hpp"



/*************************************************************************************************************************
 Class definition for Base
**************************************************************************************************************************/

/*************************************************************************************************************************
 Class definition for Connection
**************************************************************************************************************************/

/**
* Connects to an end point
*
* @param[in] pConnection - Connection instance.
* @param[in] pNetworkCredentials - Host to connect to
* @return error code or 0 (success)
*/
typedef LibGRPCWrapperResult (*PLibGRPCWrapperConnection_ConnectPtr) (LibGRPCWrapper_Connection pConnection, const char * pNetworkCredentials);

/**
* Send a request
*
* @param[in] pConnection - Connection instance.
* @return error code or 0 (success)
*/
typedef LibGRPCWrapperResult (*PLibGRPCWrapperConnection_SendRequestPtr) (LibGRPCWrapper_Connection pConnection);

/*************************************************************************************************************************
 Global functions
**************************************************************************************************************************/

/**
* retrieves the binary version of this library.
*
* @param[out] pMajor - returns the major version of this library
* @param[out] pMinor - returns the minor version of this library
* @param[out] pMicro - returns the micro version of this library
* @return error code or 0 (success)
*/
typedef LibGRPCWrapperResult (*PLibGRPCWrapperGetVersionPtr) (LibGRPCWrapper_uint32 * pMajor, LibGRPCWrapper_uint32 * pMinor, LibGRPCWrapper_uint32 * pMicro);

/**
* Returns the last error recorded on this object
*
* @param[in] pInstance - Instance Handle
* @param[in] nErrorMessageBufferSize - size of the buffer (including trailing 0)
* @param[out] pErrorMessageNeededChars - will be filled with the count of the written bytes, or needed buffer size.
* @param[out] pErrorMessageBuffer -  buffer of Message of the last error, may be NULL
* @param[out] pHasError - Is there a last error to query
* @return error code or 0 (success)
*/
typedef LibGRPCWrapperResult (*PLibGRPCWrapperGetLastErrorPtr) (LibGRPCWrapper_Base pInstance, const LibGRPCWrapper_uint32 nErrorMessageBufferSize, LibGRPCWrapper_uint32* pErrorMessageNeededChars, char * pErrorMessageBuffer, bool * pHasError);

/**
* Acquire shared ownership of an Instance
*
* @param[in] pInstance - Instance Handle
* @return error code or 0 (success)
*/
typedef LibGRPCWrapperResult (*PLibGRPCWrapperAcquireInstancePtr) (LibGRPCWrapper_Base pInstance);

/**
* Releases shared ownership of an Instance
*
* @param[in] pInstance - Instance Handle
* @return error code or 0 (success)
*/
typedef LibGRPCWrapperResult (*PLibGRPCWrapperReleaseInstancePtr) (LibGRPCWrapper_Base pInstance);

/**
* Returns the address of the SymbolLookupMethod
*
* @param[out] pSymbolLookupMethod - Address of the SymbolAddressMethod
* @return error code or 0 (success)
*/
typedef LibGRPCWrapperResult (*PLibGRPCWrapperGetSymbolLookupMethodPtr) (LibGRPCWrapper_pvoid * pSymbolLookupMethod);

/**
* Returns a PLC instance
*
* @param[in] pProtobufDefinition - String containing the proto definition
* @param[out] pConnectionInstance - Connection Instance
* @return error code or 0 (success)
*/
typedef LibGRPCWrapperResult (*PLibGRPCWrapperCreateConnectionPtr) (const char * pProtobufDefinition, LibGRPCWrapper_Connection * pConnectionInstance);

/*************************************************************************************************************************
 Function Table Structure
**************************************************************************************************************************/

typedef struct {
	void * m_LibraryHandle;
	PLibGRPCWrapperConnection_ConnectPtr m_Connection_Connect;
	PLibGRPCWrapperConnection_SendRequestPtr m_Connection_SendRequest;
	PLibGRPCWrapperGetVersionPtr m_GetVersion;
	PLibGRPCWrapperGetLastErrorPtr m_GetLastError;
	PLibGRPCWrapperAcquireInstancePtr m_AcquireInstance;
	PLibGRPCWrapperReleaseInstancePtr m_ReleaseInstance;
	PLibGRPCWrapperGetSymbolLookupMethodPtr m_GetSymbolLookupMethod;
	PLibGRPCWrapperCreateConnectionPtr m_CreateConnection;
} sLibGRPCWrapperDynamicWrapperTable;

#endif // __LIBGRPCWRAPPER_DYNAMICHEADER_CPPTYPES

